# Makefile automatically generated by ghdl
# Version: GHDL 0.26 (20070408) [Sokcho edition] - GCC back-end code generator
# Command used to generate this makefile:
# /usr/lib/ghdl/bin/ghdl --gen-makefile tb_ucpu

GHDL=/usr/lib/ghdl/bin/ghdl
GHDLFLAGS=
DIR=uCPU

# Default target
all: tb_ucpu

clean:
	rm -f *.o *~ tb_ucpu work-obj93.cf

zip:
	cd .. ; zip -r $(DIR).zip $(DIR) }

# Elaboration target
tb_ucpu: std_logic_extra.o ucpu.o rom.o ram.o portabidir.o ioport.o tb_ucpu.o 
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: tb_ucpu
	$(GHDL) -r tb_ucpu $(GHDLRUNFLAGS)

# Targets to analyze files
portabidir.o: portabidir.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
ioport.o: ioport.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
ucpu.o: ucpu.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
rom.o: rom.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
ram.o: ram.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
tb_ucpu.o: tb_ucpu.vhd std_logic_extra.o ucpu.o rom.o ram.o portabidir.o ioport.o
	$(GHDL) -a $(GHDLFLAGS) $<
std_logic_extra.o: std_logic_extra.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
